apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: lab
spec:
  version: 9.0.1
  nodeSets:
  - name: hot
    count: 3
    config:
      node.store.allow_mmap: false
  - name: master
    count: 3
    config:
      node.store.allow_mmap: false
  - name: frozen
    count: 3
    config:
      node.store.allow_mmap: false
EOF
