apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.mariadb-tika.yaml.translated -o manifests/paperless/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.mariadb-tika.yaml.translated -o manifests/paperless/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: broker
    spec:
      containers:
        - image: docker.io/library/redis:7
          name: broker
          volumeMounts:
            - mountPath: /data
              name: redisdata
      restartPolicy: Always
      volumes:
        - name: redisdata
          persistentVolumeClaim:
            claimName: redisdata
