apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.mariadb-tika.yaml.translated -o manifests/paperless/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.mariadb-tika.yaml.translated -o manifests/paperless/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: webserver
    spec:
      containers:
        - env:
            - name: PAPERLESS_DBENGINE
              value: mariadb
            - name: PAPERLESS_DBHOST
              value: db
            - name: PAPERLESS_DBPASS
              value: paperless
            - name: PAPERLESS_DBPORT
              value: "3306"
            - name: PAPERLESS_DBUSER
              value: paperless
            - name: PAPERLESS_OCR_LANGUAGE
              valueFrom:
                configMapKeyRef:
                  key: PAPERLESS_OCR_LANGUAGE
                  name: docker-compose-env
            - name: PAPERLESS_REDIS
              value: redis://broker:6379
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: PAPERLESS_SECRET_KEY
                  name: docker-compose-env
            - name: PAPERLESS_TIKA_ENABLED
              value: "1"
            - name: PAPERLESS_TIKA_ENDPOINT
              value: http://tika:9998
            - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
              value: http://gotenberg:3000
            - name: PAPERLESS_TIME_ZONE
              valueFrom:
                configMapKeyRef:
                  key: PAPERLESS_TIME_ZONE
                  name: docker-compose-env
            - name: PAPERLESS_URL
              valueFrom:
                configMapKeyRef:
                  key: PAPERLESS_URL
                  name: docker-compose-env
            - name: USERMAP_GID
              valueFrom:
                configMapKeyRef:
                  key: USERMAP_GID
                  name: docker-compose-env
            - name: USERMAP_UID
              valueFrom:
                configMapKeyRef:
                  key: USERMAP_UID
                  name: docker-compose-env
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          name: webserver
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: data
            - mountPath: /usr/src/paperless/media
              name: media
            - mountPath: /usr/src/paperless/export
              name: webserver-claim2
            - mountPath: /usr/src/paperless/consume
              name: webserver-claim3
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: webserver-claim2
          persistentVolumeClaim:
            claimName: webserver-claim2
        - name: webserver-claim3
          persistentVolumeClaim:
            claimName: webserver-claim3
