apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: qbittorrent-claim0
  name: qbittorrent-claim0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Ti
