apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: qbittorrent-claim1
  name: qbittorrent-claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Ti
