---
- name: Deploy a basic Linux server
  hosts: all
  gather_facts: false
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: true
        upgrade: dist

    - name: Install basic packages
      become: true
      apt:
        name:
          - git
          - curl
          - vim
          - unzip 
          - python3-pip
          - zsh 
          - autoconf 
          - htop 
          - eslint 
          - gettext 
          - luajit 
          - neovim 
          - npm
          - stow 
          - tmux
          - openssl 
          - ripgrep 
          - fzf 
          - kitty-terminfo
        state: present

    - name: Test for dotfiles
      ansible.builtin.stat:
        path: ~/git/dotfile/.git
      register: file_check

    - name: Clone dotfiles repository
      block:
        - name: Ensure .ssh directory exists
          file:
            path: ~/.ssh
            state: directory
            mode: '0700'
  
        - name: Copy GitHub SSH keys
          copy:
            src:  /Users/bdw/.ssh/github_rsa
            dest: ~/.ssh/
            mode: '0600'
  
        - name: Copy GitHub SSH keys
          copy:
            src:  /Users/bdw/.ssh/github_rsa.pub
            dest: ~/.ssh/
            mode: '0600'
  
        - name: Copy SSH config
          copy:
            src: /Users/bdw/.ssh/config
            dest: ~/.ssh/config
            mode: '0600'
  
        - name: Copy known_hosts
          copy:
            src: /Users/bdw/.ssh/known_hosts
            dest: ~/.ssh/known_hosts
            mode: '0600'
  
        - name: Ensure git/dotfiles exists
          file:
            dest: ~/git/dotfiles
            state: directory
  
        - name: Clone dotfiles repository
          git:
            repo: 'git@github.com:wortmanb/dotfiles.git'
            dest: '~/git/dotfiles/'
            clone: true
            update: true
          environment:
            GIT_TERMINAL_PROMPT: 0 
      when: file_check.stat.exists == False

    - name: Empty .ssh directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "/home/bret/.ssh/*"

    - name: Setup dotfiles
      shell: >
        './git/dotfiles/__setup/linux.sh'

    - name: Install dotfiles
      shell: >
        './git/dotfiles/setup.sh'

    - name: Change shell to zsh
      shell: >
        'chsh -s $(which zsh)'
