---
- name: Setup proxy
  become: true
  hosts: proxy

  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - apache2-utils
        - docker.io
        - docker-compose
        - containerd

    - name: Copy docker compose file
      copy:
        src: ~/git/homelab/ansible/proxy-docker-compose.yml
        dest: /root/docker-compose.yml

    - name: Apply docker compose file
      command: docker-compose -f /root/docker-compose.yml up -d
