---
- name: Setup Kubernetes Control Plane or Master Node
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: true
        upgrade: true

    - name: Install Docker
      apt:
        name: 
          - docker.io
          - containerd
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add Kubernetes APT key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes APT repository
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: true

    - name: Hold kubelet, kubeadm, and kubectl at current version
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: true
        force: true
        allow_downgrade: true
        allow_unauthenticated: true
        default_release: "{{ ansible_distribution_release }}"
        dpkg_options: "hold"

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Remove swap entry from /etc/fstab
      mount:
        name: swap
        fstype: swap
        state: absent

    #    - name: Enable net.bridge.bridge-nf-call-iptables
    #      sysctl:
    #        name: net.bridge.bridge-nf-call-iptables
    #        value: 1
    #        state: present
    #        reload: true
    #
    #    - name: Enable net.bridge.bridge-nf-call-ip6tables
    #      sysctl:
    #        name: net.bridge.bridge-nf-call-ip6tables
    #        value: 1
    #        state: present
    #        reload: true
