---
- name: Setup worker nodes for Kubernetes cluster
  hosts: workers
  become: true
  vars:
    control_plane_nodes: ["controlplane1.example.com", "controlplane2.example.com"]
    pod_network_cidr: "192.168.0.0/16"
  
  tasks:
    - name: Initialize the worker node
      command: kubeadm join {{ control_plane_nodes[0] }}:6443 --token <token> --discovery-token-ca-cert-hash sha256:<hash>

    - name: Restart kubelet service
      systemd:
          name: kubelet
          state: restarted
          enabled: true
