---
- name: Setup First Kubernetes Control Plane Node
  hosts: k8s_cp
  gather_facts: false
  become: true

  tasks:
    - name: Update hosts file
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          192.168.10.71 kube01.lab.thewortmans.org cp.lab.thewortmans.org
          192.168.10.72 kube02.lab.thewortmans.org cp.lab.thewortmans.org
          192.168.10.73 kube03.lab.thewortmans.org cp.lab.thewortmans.org

    - name: Initialize Kubernetes Control Plane
      command: kubeadm init --pod-network-cidr=192.168.100.0/24 --upload-certs --control-plane-endpoint cp.lab.thewortmans.org
      register: kubeadm_init

    - name: Create .kube directory
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy kubeconfig to user's home
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      when: kubeadm_init.changed

    - name: Install Kube-Router CNI
      become: true
      shell: |
        mkdir -p kube-router
        cd kube-router
        wget https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
        export DATESTAMP=$(date +%Y.%m.%d)
        mv kubeadm-kuberouter.yaml kubeadm-kuberouter-${DATESTAMP}.yaml
        kubectl apply -f kubeadm-kuberouter-${DATESTAMP}.yaml
      when: kubeadm_init.changed
      
