---
- name: Upgrade Elasticsearch Cluster
  hosts: elasticsearch_all
  become: yes
  serial: 1
  user: bret
  gather_facts: no

  vars:
    ansible_ssh_common_args: '-o IdentityFile=~/.ssh/github_rsa'

  tasks:
    - name: Add Elasticsearch repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
        sudo apt -y update

    - name: Install the latest version of Elasticsearch
      apt:
        name: elasticsearch
        state: latest
      when: "'elasticsearch' in group_names"

    - name: Ensure Elasticsearch is enabled and started
      service:
        name: elasticsearch
        enabled: yes
        state: restarted
      when: "'elasticsearch' in group_names"

    - name: Install the latest version of Kibana
      apt:
        name: kibana
        state: latest
      when: "'kibana' in group_names"

    - name: Ensure Kibana is enabled and started
      service:
        name: kibana
        enabled: yes
        state: restarted
      when: "'kibana' in group_names"
